import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useSearchParams } from 'react-router-dom'
import type { Product } from '../types'
import { orderService,productService } from '../services'
import { AccountPageHeader } from '../components/account/AccountPageHeader'
import { StatCard } from '../components/account/StatCard'
import { StatusBadge } from '../components/account/StatusBadge'
import { AppLogo } from '../components/storefront/AppLogo'
import { Button } from '../components/ui/Button'
import { Icon } from '../components/ui/Icon'
import { ConfirmationDialog,Dialog,EmptyState,ErrorState,FileUpload,Skeleton,useToast } from '../components/feedback'
import { formatCurrency } from '../lib/currency'

export function AdminPage(){
  const [params,setParams]=useSearchParams(); const tab=params.get('tab')??'overview'
  const products=useQuery({queryKey:['products'],queryFn:productService.list}); const orders=useQuery({queryKey:['orders'],queryFn:orderService.list})
  const [search,setSearch]=useState(''); const [editing,setEditing]=useState<Product|null>(null); const [confirming,setConfirming]=useState<Product|null>(null); const [hidden,setHidden]=useState<string[]>([]); const toast=useToast()
  if(products.isError||orders.isError)return <ErrorState description="Admin mock data could not be loaded." onRetry={()=>void Promise.all([products.refetch(),orders.refetch()])}/>
  if(products.isLoading||orders.isLoading)return <div className="grid gap-4"><Skeleton className="h-20"/><Skeleton className="h-72"/></div>
  const productList=products.data??[]; const orderList=orders.data??[]; const lowStock=productList.filter(p=>p.deliveryType==='ready-made'&&(p.stock??0)<10)
  function toggle(product:Product){setHidden(items=>items.includes(product.id)?items.filter(id=>id!==product.id):[...items,product.id]);setConfirming(null);toast({message:`${product.name} visibility updated for this demo.`,tone:'success'})}
  return <>
    <AccountPageHeader title={tab==='overview'?'Operations overview':tab[0].toUpperCase()+tab.slice(1)} description="Frontend-only operational controls using existing Subly mock data." action={<div className="flex flex-wrap gap-2"><Button variant="secondary"><Icon name="file-check"/>Export demo</Button><Button onClick={()=>setEditing(productList[0]??null)}><Icon name="plus"/>Add product</Button></div>}/>
    {tab==='overview'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-5"><StatCard icon="wallet" label="Mock order value" value={formatCurrency(orderList.reduce((sum,o)=>sum+o.total,0))}/><StatCard icon="package" label="Orders" value={String(orderList.length)} detail={`${orderList.filter(o=>o.status!=='completed').length} need attention`}/><StatCard icon="box" label="Active products" value={String(productList.length-hidden.length)}/><StatCard icon="alert-triangle" label="Low stock" value={String(lowStock.length)} detail="Restock required"/><StatCard icon="clock" label="Pending fulfillment" value={String(orderList.filter(o=>['pending','under-review','processing'].includes(o.status)).length)}/></div><div className="mt-6 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><InventoryTable products={productList.slice(0,5)} hidden={hidden} search={search} setSearch={setSearch} onEdit={setEditing} onToggle={setConfirming}/><section className="border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Pending actions</h2><ul className="mt-3 divide-y divide-slate-200">{[['Orders awaiting fulfillment',orderList.filter(o=>o.status==='processing').length,'orders'],['Products needing restock',lowStock.length,'inventory'],['Assisted top-ups',productList.filter(p=>p.deliveryType==='assisted').length,'fulfillment']].map(([label,count,target])=><li key={String(label)} className="flex items-center justify-between gap-3 py-4 text-sm"><span>{label} <b>{count}</b></span><button onClick={()=>setParams({tab:String(target)})} className="inline-flex items-center gap-1 font-semibold text-primary">Review <Icon name="arrow-right" className="size-4"/></button></li>)}</ul></section></div><section className="mt-5 border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Recent order operations</h2><OrderTable orders={orderList.slice(0,4)}/></section></>}
    {tab==='products'&&<InventoryTable products={productList} hidden={hidden} search={search} setSearch={setSearch} onEdit={setEditing} onToggle={setConfirming}/>} 
    {tab==='orders'&&<section className="border border-slate-200 bg-white p-5"><OrderTable orders={orderList}/></section>}
    {tab==='inventory'&&<section className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Instant-account inventory</h2><p className="mt-2 text-sm text-slate-600">Counts only—no credentials are stored or displayed.</p><div className="mt-4 divide-y divide-slate-200">{productList.filter(p=>p.deliveryType==='ready-made').map(p=><div key={p.id} className="grid gap-2 py-4 text-sm sm:grid-cols-[minmax(10rem,1fr)_repeat(3,7rem)]"><b>{p.name}</b><span><small className="text-slate-500">Available</small><br/>{p.stock??0}</span><span><small className="text-slate-500">Reserved</small><br/>0</span><span><small className="text-slate-500">Delivered</small><br/>Demo</span></div>)}</div></section>}
    {tab==='fulfillment'&&<section className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Assisted fulfillment</h2><p className="mt-2 text-sm text-slate-600">Only non-sensitive mock customer identifiers are shown.</p>{orderList.some(o=>o.items.some(i=>i.product.deliveryType==='assisted'))?<OrderTable orders={orderList.filter(o=>o.items.some(i=>i.product.deliveryType==='assisted'))}/>:<div className="mt-4"><EmptyState title="No assisted orders" description="Assisted top-up orders will appear here."/></div>}</section>}
    <Dialog open={!!editing} onClose={()=>setEditing(null)} title={editing?'Edit product image':'Product editor'} description="Changes remain in frontend state only."><FileUpload/><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Image fit<select className="mt-2 w-full rounded-card border border-slate-300 bg-white p-2"><option>Contain</option><option>Cover</option></select></label><label className="text-sm font-semibold">Fulfillment type<select className="mt-2 w-full rounded-card border border-slate-300 bg-white p-2"><option>INSTANT_ACCOUNT</option><option>ASSISTED_TOPUP</option></select></label></div><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={()=>{setEditing(null);toast({message:'Product preview saved locally.',tone:'success'})}}>Save preview</Button></div></Dialog>
    <ConfirmationDialog open={!!confirming} onClose={()=>setConfirming(null)} onConfirm={()=>confirming&&toggle(confirming)} title={`${hidden.includes(confirming?.id??'')?'Enable':'Disable'} ${confirming?.name??'product'}?`} description="This changes storefront visibility in frontend state only." confirmLabel="Confirm visibility change" destructive={!hidden.includes(confirming?.id??'')}/>
  </>
}

function InventoryTable({products,hidden,search,setSearch,onEdit,onToggle}:{products:Product[];hidden:string[];search:string;setSearch:(value:string)=>void;onEdit:(product:Product)=>void;onToggle:(product:Product)=>void}){const visible=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));return <section className="border border-slate-200 bg-white p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-bold">Product inventory</h2><div className="relative sm:w-64"><Icon name="search" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products" aria-label="Search products" className="min-h-10 w-full rounded-card border border-slate-300 pl-9 pr-3"/></div></div>{visible.length?<div className="mt-4 divide-y divide-slate-200">{visible.map(p=><div key={p.id} className="grid gap-3 py-4 text-sm sm:grid-cols-[1.5fr_1fr_6rem_7rem_6rem] sm:items-center"><div className="flex min-w-0 items-center gap-3"><AppLogo product={p} className="size-10 rounded"/><b className="truncate">{p.name}</b></div><span className="break-all text-xs font-semibold text-slate-600">{p.deliveryType==='ready-made'?'INSTANT_ACCOUNT':'ASSISTED_TOPUP'}</span><span className={(p.stock??0)<10?'text-amber-700':'text-emerald-700'}>{p.deliveryType==='ready-made'?`${p.stock??0} stock`:'N/A'}</span><button role="switch" aria-checked={!hidden.includes(p.id)} onClick={()=>onToggle(p)} className={`w-fit rounded-full px-3 py-1 text-xs ${hidden.includes(p.id)?'bg-slate-200':'bg-emerald-100 text-emerald-700'}`}>{hidden.includes(p.id)?'Hidden':'Visible'}</button><button onClick={()=>onEdit(p)} className="text-left font-semibold text-primary sm:text-center">Edit</button></div>)}</div>:<div className="mt-4"><EmptyState title="No products found" description="Try another search."/></div>}</section>}
function OrderTable({orders}:{orders:Awaited<ReturnType<typeof orderService.list>>}){return <div className="mt-4 divide-y divide-slate-200">{orders.map(o=><div key={o.id} className="grid gap-3 py-4 text-sm sm:grid-cols-[1fr_1.2fr_7rem_8rem] sm:items-center"><div className="min-w-0"><b className="break-all">{o.reference}</b><p className="truncate text-xs text-slate-500">{o.customer.email}</p></div><span className="break-words">{o.items.map(i=>i.product.name).join(', ')}</span><b>{formatCurrency(o.total)}</b><StatusBadge status={o.status}/></div>)}</div>}
