import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Container } from '../components/layout/Container'
import { AppLogo } from '../components/storefront/AppLogo'
import { ProductCard } from '../components/storefront/ProductCard'
import { Button } from '../components/ui/Button'
import { Icon } from '../components/ui/Icon'
import { EmptyState } from '../components/feedback'
import { products } from '../data/mockData'
import { useCart } from '../features/cart'
import { formatCurrency } from '../lib/currency'

export function CartPage(){
  const cart=useCart(); const navigate=useNavigate(); const [promo,setPromo]=useState(''); const [message,setMessage]=useState('')
  function apply(e:FormEvent){e.preventDefault();setMessage(promo.trim()?'This promo code is invalid or unavailable.':'Enter a promo code to continue.')}
  if(!cart.items.length)return <Container className="py-14"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Your selection</p><h1 className="mt-2 text-3xl font-extrabold">Your cart</h1></div><EmptyState title="Your cart is empty" description="Browse trusted tools and add something to get started." action={<Link className="inline-flex items-center gap-2 rounded-card bg-primary px-5 py-3 font-bold text-white" to="/shop">Browse products <Icon name="arrow-right" className="size-4"/></Link>}/></Container>
  return <Container className="py-9">
    <nav className="flex items-center gap-2 text-sm text-slate-500"><Link to="/">Home</Link><span>/</span><span className="text-slate-800">Cart</span></nav>
    <div className="mt-7 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Your selection</p><h1 className="mt-2 text-3xl font-extrabold">Your cart</h1><p className="mt-2 text-slate-600">Review products, delivery details and quantities.</p></div><span className="text-sm text-slate-500">{cart.itemCount} items</span></div>
    <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_21rem]">
      <section className="overflow-hidden border border-slate-200 bg-white"><div className="hidden grid-cols-[1.55fr_1fr_6rem_8rem] border-b border-slate-200 bg-slate-50/60 px-5 py-3 text-xs font-semibold uppercase text-slate-500 md:grid"><span>Product</span><span>Details</span><span>Price</span><span>Quantity</span></div>{cart.items.map(item=><article key={item.product.id} className="grid gap-5 border-b border-slate-200 p-5 last:border-b-0 md:grid-cols-[1.55fr_1fr_6rem_8rem] md:items-center"><div className="flex min-w-0 gap-4"><div className="grid size-16 shrink-0 place-items-center rounded-card bg-slate-50 p-2"><AppLogo product={item.product} className="size-12"/></div><div className="min-w-0"><Link className="break-words font-bold hover:text-primary" to={'/product/'+item.product.slug}>{item.product.name} — 1 Month</Link><p className="mt-1 text-xs font-medium text-slate-500">{item.product.deliveryType==='ready-made'?'Ready-made access':'Assisted activation'}</p><button onClick={()=>cart.removeItem(item.product.id)} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-danger"><Icon name="trash" className="size-3.5"/>Remove</button></div></div><div className="grid grid-cols-2 gap-3 text-sm md:block"><p><span className="text-xs text-slate-500">Validity</span><br/><b>{item.product.validity}</b></p><p className="md:mt-3"><span className="text-xs text-slate-500">Delivery</span><br/><b>{item.product.deliveryMinutes}–{item.product.deliveryMinutes+5} min</b></p></div><div><span className="text-xs text-slate-500 md:hidden">Price </span><b>{formatCurrency(item.product.price)}</b></div><div className="flex h-10"><button className="grid w-10 place-items-center rounded-l-card border border-slate-200" onClick={()=>cart.updateQuantity(item.product.id,item.quantity-1)} aria-label={'Decrease '+item.product.name+' quantity'}><Icon name="minus" className="size-4"/></button><span className="grid w-10 place-items-center border-y border-slate-200">{item.quantity}</span><button className="grid w-10 place-items-center rounded-r-card border border-slate-200" onClick={()=>cart.updateQuantity(item.product.id,item.quantity+1)} aria-label={'Increase '+item.product.name+' quantity'}><Icon name="plus" className="size-4"/></button></div></article>)}
        <div className="border-t border-slate-200 p-5"><Link to="/shop" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><Icon name="arrow-left" className="size-4"/>Continue shopping</Link><form onSubmit={apply} className="mt-6 border-t border-slate-200 pt-6"><label htmlFor="promo" className="text-sm font-bold">Promo code</label><div className="mt-3 flex gap-2"><div className="relative min-w-0 flex-1"><Icon name="tag" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input id="promo" value={promo} onChange={e=>setPromo(e.target.value)} placeholder="Enter promo code" className="min-h-11 w-full rounded-card border border-slate-200 pl-10 pr-3"/></div><Button variant="secondary">Apply</Button></div>{message&&<p role="alert" className="mt-2 flex items-center gap-2 text-sm text-danger"><Icon name="circle-x" className="size-4"/>{message}</p>}</form></div>
      </section>
      <aside className="h-fit border border-slate-200 bg-white p-6 shadow-[0_12px_35px_rgba(15,23,42,.07)] lg:sticky lg:top-24"><h2 className="text-xl font-bold">Order summary</h2><dl className="mt-6 grid gap-4 text-sm"><div className="flex justify-between"><dt className="text-slate-600">Subtotal</dt><dd className="font-semibold">{formatCurrency(cart.subtotal)}</dd></div><div className="flex justify-between border-t border-slate-200 pt-5 text-xl"><dt className="font-bold">Total</dt><dd className="font-extrabold">{formatCurrency(cart.subtotal)}</dd></div></dl><Button onClick={()=>navigate('/checkout')} className="mt-6 w-full">Proceed to checkout</Button><p className="mt-4 text-center text-xs leading-5 text-slate-500">Taxes and payment fees, if any, are shown before payment.</p><div className="mt-6 border-t border-slate-200 pt-5"><p className="flex items-center gap-2 text-sm font-semibold"><Icon name="lock" className="size-4 text-emerald-600"/>Secure checkout</p><p className="mt-2 text-xs leading-5 text-slate-500">Your order information is kept private and secure.</p></div></aside>
    </div>
    <section className="mt-12 border-t border-slate-200 pt-9"><h2 className="text-2xl font-bold">You may also like</h2><div className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-4">{products.filter(p=>!cart.items.some(i=>i.product.id===p.id)).slice(0,4).map(p=><ProductCard compact key={p.id} product={p}/>)}</div></section>
    <div className="sticky bottom-0 z-30 -mx-4 mt-6 flex items-center justify-between border-t border-slate-200 bg-white/95 p-4 shadow-[0_-8px_24px_rgba(15,23,42,.08)] backdrop-blur lg:hidden"><div><span className="text-xs text-slate-500">Total</span><b className="block">{formatCurrency(cart.subtotal)}</b></div><Button onClick={()=>navigate('/checkout')}>Checkout</Button></div>
  </Container>
}
