import { useState } from 'react'
import { useForm, useWatch } from 'react-hook-form'
import { z } from 'zod'
import { Link, useNavigate } from 'react-router-dom'
import { useCart } from '../features/cart'
import { orderService } from '../services'
import { Container } from '../components/layout/Container'
import { EmptyState } from '../components/feedback'
import { Button } from '../components/ui/Button'
import { Icon } from '../components/ui/Icon'
import { OrderSummary } from '../components/checkout/OrderSummary'
import { PaymentMethodOption } from '../components/checkout/PaymentMethodOption'

const schema=z.object({email:z.email('Enter a valid delivery email.'),terms:z.boolean().refine(value=>value,{message:'You must agree to the terms to continue.'}),paymentMethod:z.enum(['bank-transfer','usdt','subly-points','contact','mock-failure'])})
type FormValues=z.infer<typeof schema>
const methods=[['bank-transfer','bank','Bank transfer','Manual review'],['usdt','wallet','USDT','Demo selection'],['subly-points','sparkles','Subly Points','Not available'],['contact','message-circle','Contact checkout','Demo only']] as const

export function CheckoutPage(){
  const cart=useCart(); const navigate=useNavigate(); const [submitError,setSubmitError]=useState('')
  const {register,handleSubmit,setValue,setError,control,formState:{errors,isSubmitting}}=useForm<FormValues>({defaultValues:{email:'',terms:false,paymentMethod:'bank-transfer'}})
  const method=useWatch({control,name:'paymentMethod'})
  async function submit(values:FormValues){setSubmitError('');const parsed=schema.safeParse(values);if(!parsed.success){for(const issue of parsed.error.issues)setError(issue.path[0] as keyof FormValues,{message:issue.message});return}try{await orderService.createOrder({items:cart.items,customer:{email:values.email},paymentMethod:values.paymentMethod,subtotal:cart.subtotal});cart.clear();navigate('/order/success')}catch{setSubmitError('The demo order could not be submitted. Your cart has not been changed.');navigate('/order/failed')}}
  if(!cart.items.length)return <Container className="py-16"><EmptyState title="Your cart is empty" description="Add a product before continuing to checkout." action={<Link to="/shop" className="inline-flex items-center gap-2 rounded-card bg-primary px-5 py-3 font-bold text-white">Browse products <Icon name="arrow-right" className="size-4"/></Link>}/></Container>
  const description=method==='bank-transfer'?'Your order enters manual review. No real bank details or receiving account are used in this frontend demo.':method==='usdt'?'This is a visual demo choice only. No wallet address, blockchain request or transaction is created.':method==='subly-points'?'Subly Points payments are not available in this frontend stage. Choose another method to continue.':'Your preference is recorded for the demo order. No WhatsApp, Telegram or external message is sent.'
  return <Container className="py-8">
    <div className="mx-auto mb-8 flex max-w-xl items-start justify-center text-xs sm:text-sm">{[['circle-check','Cart'],['credit-card','Checkout'],['clock','Order status']].map(([icon,label],index)=><div key={label} className="contents"><div className={"flex min-w-16 flex-col items-center gap-1.5 text-center "+(index<2?'text-primary':'text-slate-400')}><span className={"grid size-8 place-items-center rounded-full "+(index===1?'bg-primary text-white':index===0?'bg-blue-50 text-primary':'bg-slate-100')}><Icon name={icon as 'clock'} className="size-4"/></span><span className="font-semibold">{label}</span></div>{index<2&&<span className={"mt-4 h-px w-10 sm:w-24 "+(index===0?'bg-primary':'bg-slate-200')}/>}</div>)}</div>
    <div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Secure checkout</p><h1 className="mt-2 text-3xl font-extrabold">Complete your order</h1><p className="mt-2 text-slate-600">Confirm your delivery and payment details.</p></div>
    <form onSubmit={handleSubmit(submit)} className="mt-8 grid gap-8 lg:grid-cols-[1.45fr_.8fr]">
      <div className="space-y-8">
        <section><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-blue-50 text-sm font-bold text-primary">1</span><div><h2 className="text-lg font-bold">Delivery details</h2><p className="text-sm text-slate-500">Where should order updates be sent?</p></div></div><label htmlFor="delivery-email" className="mt-5 block text-sm font-semibold">Delivery email</label><div className="relative mt-2"><Icon name="mail" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input id="delivery-email" type="email" {...register('email')} aria-invalid={!!errors.email} className={"min-h-11 w-full rounded-card border bg-white pl-10 pr-4 "+(errors.email?'border-red-400':'border-slate-200 focus:border-primary')} placeholder="customer@example.com"/></div><p className={(errors.email?'text-danger':'text-slate-500')+" mt-1.5 text-sm"}>{errors.email?.message??'Access details and order updates will be sent here.'}</p></section>
        <section className="border-t border-slate-200 pt-8"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-blue-50 text-sm font-bold text-primary">2</span><div><h2 className="text-lg font-bold">Payment method</h2><p className="text-sm text-slate-500">Demo choices only — no payment is processed.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{methods.map(([value,icon,title,detail])=><PaymentMethodOption key={value} value={value} icon={icon} title={title} description={detail} selected={method===value} onChange={value=>setValue('paymentMethod',value)}/>)}</div><div className={"mt-4 border p-4 "+(method==='subly-points'?'border-amber-200 bg-amber-50':'border-blue-100 bg-blue-50/60')}><div className="flex gap-3"><Icon name={method==='subly-points'?'alert-triangle':'info'} className={"mt-0.5 "+(method==='subly-points'?'text-amber-700':'text-primary')}/><div><h3 className="font-bold">{method==='bank-transfer'?'Bank transfer review':method==='usdt'?'USDT demo selection':method==='subly-points'?'Subly Points unavailable':'Contact checkout demo'}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{description}</p></div></div></div><details className="mt-3 text-sm"><summary className="cursor-pointer text-slate-500">Developer test option</summary><label className="mt-3 flex items-center gap-2"><input type="radio" checked={method==='mock-failure'} onChange={()=>setValue('paymentMethod','mock-failure')} className="accent-primary"/>Use controlled demo submission failure</label></details></section>
        <section className="border-t border-slate-200 pt-8"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-blue-50 text-sm font-bold text-primary">3</span><div><h2 className="text-lg font-bold">Review and submit</h2><p className="text-sm text-slate-500">Confirm your consent before continuing.</p></div></div><label className="mt-5 flex items-start gap-3"><input type="checkbox" {...register('terms')} className="mt-0.5 size-5 accent-primary"/><span className="text-sm leading-6">I agree to the <Link className="font-medium text-primary" to="/terms-of-service">Terms of Service</Link> and <Link className="font-medium text-primary" to="/privacy-policy">Privacy Policy</Link>.</span></label>{errors.terms&&<p className="mt-2 flex items-center gap-2 text-sm text-danger"><Icon name="circle-x" className="size-4"/>{errors.terms.message}</p>}{submitError&&<p role="alert" className="mt-3 flex gap-2 border border-red-200 bg-red-50 p-3 text-sm text-danger"><Icon name="circle-x" className="size-4"/>{submitError}</p>}<Button loading={isSubmitting} disabled={method==='subly-points'} className="mt-5 w-full">{method==='bank-transfer'?'Submit order for review':'Continue with demo order'}</Button><Link to="/cart" className="mt-4 flex items-center justify-center gap-2 text-sm font-semibold text-primary"><Icon name="arrow-left" className="size-4"/>Return to cart</Link></section>
      </div>
      <OrderSummary items={cart.items} subtotal={cart.subtotal}/>
    </form>
    <section id="support" className="mt-9 flex flex-col gap-4 border border-slate-200 bg-slate-50/60 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-blue-50 text-primary"><Icon name="headphones"/></span><div><b>Need help with checkout?</b><p className="mt-1 text-sm text-slate-600">Our support team can answer general order questions.</p></div></div><a href="mailto:support@subly.example" className="rounded-card border border-primary px-4 py-2 text-center text-sm font-semibold text-primary">Contact support</a></section>
  </Container>
}
