import { Link } from 'react-router-dom'
import { Container } from '../components/layout/Container'
import { Icon, type IconName } from '../components/ui/Icon'

const steps:{icon:IconName;title:string;description:string}[]=[
  {icon:'search',title:'Browse tools',description:'Compare categories and find the right product.'},
  {icon:'file-check',title:'Review details',description:'Check validity, delivery type and requirements.'},
  {icon:'cart',title:'Add to cart',description:'Choose a quantity and review your selection.'},
  {icon:'credit-card',title:'Choose payment',description:'Select an available demo payment method.'},
  {icon:'shield-check',title:'Confirmation',description:'Your order is reviewed before fulfilment.'},
  {icon:'package',title:'Fulfilment begins',description:'Access is prepared after confirmation.'},
  {icon:'headphones',title:'Get support',description:'Track the order or contact the support team.'},
]

export function HowItWorksPage(){return <>
  <section className="border-b border-slate-200 bg-white">
    <Container className="grid gap-10 py-14 md:grid-cols-[.9fr_1.1fr] md:items-center">
      <div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Simple. Secure. Supported.</p><h1 className="mt-3 text-4xl font-extrabold">How Subly works</h1><p className="mt-5 max-w-lg leading-7 text-slate-600">Choose a digital tool, review exactly how it is fulfilled, and place your order with clear expectations from checkout to access.</p><Link className="mt-6 inline-flex items-center gap-2 rounded-card bg-primary px-5 py-3 font-bold text-white" to="/shop">Explore tools <Icon name="arrow-right" className="size-4"/></Link></div>
      <div className="relative grid grid-cols-3 items-start gap-2 sm:gap-5">{[['cart','Order placed','Your selection is recorded.'],['shield-check','Order review','Details are checked.'],['mail','Access delivered','Sent after confirmation.']].map(([icon,title,text],index)=><div key={title} className="relative text-center">{index<2&&<span className="absolute left-[64%] top-7 hidden h-px w-[72%] bg-blue-200 sm:block"/>}<span className={"relative mx-auto grid size-14 place-items-center rounded-full border "+(index===1?'border-primary bg-primary text-white':'border-blue-200 bg-blue-50 text-primary')}><Icon name={icon as IconName} className="size-6"/></span><b className="mt-3 block text-sm">{title}</b><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>)}</div>
    </Container>
  </section>
  <Container className="py-14"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">The customer journey</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">From product to access in seven clear steps</h2></div><ol className="mx-auto mt-10 grid max-w-6xl grid-cols-2 gap-x-5 gap-y-8 md:grid-cols-4">{steps.map((step,index)=><li key={step.title} className="relative"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-card bg-blue-50 text-primary"><Icon name={step.icon}/></span><span className="text-xs font-bold text-blue-500">0{index+1}</span></div><h3 className="mt-3 font-bold">{step.title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{step.description}</p></li>)}</ol></Container>
  <section className="border-y border-slate-200 bg-slate-50/60"><Container className="py-14"><div className="mx-auto max-w-2xl text-center"><h2 className="text-2xl font-bold">Two ways we deliver</h2><p className="mt-2 text-slate-600">Every product page tells you which route applies before you buy.</p></div><div className="mx-auto mt-8 grid max-w-5xl gap-5 md:grid-cols-2"><article className="border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-card bg-blue-50 text-primary"><Icon name="zap"/></span><div><h3 className="text-lg font-bold">Ready-made access</h3><p className="text-xs font-semibold text-primary">Typically the fastest route</p></div></div><ul className="mt-5 grid gap-3 text-sm text-slate-700">{['Availability shown before purchase','Pre-stocked digital access','Delivered after payment confirmation','Change credentials after first login'].map(t=><li key={t} className="flex gap-2"><Icon name="check" className="size-4 text-emerald-600"/>{t}</li>)}</ul></article><article className="border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-card bg-teal/10 text-teal"><Icon name="package"/></span><div><h3 className="text-lg font-bold">Assisted activation</h3><p className="text-xs font-semibold text-teal">Managed fulfilment</p></div></div><ul className="mt-5 grid gap-3 text-sm text-slate-700">{['Required account details are clearly listed','Activation begins after confirmation','Timing depends on the selected product','Updates remain available in your order'].map(t=><li key={t} className="flex gap-2"><Icon name="check" className="size-4 text-teal"/>{t}</li>)}</ul></article></div></Container></section>
  <section className="bg-navy text-white"><Container className="py-14"><div className="mx-auto max-w-2xl text-center"><h2 className="text-2xl font-bold">Clear at every stage</h2><p className="mt-2 text-blue-200">Subly separates order receipt, payment review and fulfilment so you always know what happens next.</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['lock','Secure handling','Your order information is handled carefully.'],['shield-check','Confirmation first','Fulfilment starts only after confirmation.'],['clock','Visible timing','Delivery estimates appear before purchase.'],['headphones','Human support','Help is available when an order needs attention.']].map(([icon,title,text])=><div key={title} className="border-t border-white/15 pt-4"><Icon name={icon as IconName} className="size-6 text-soft-teal"/><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-blue-200">{text}</p></div>)}</div></Container></section>
  <Container className="py-14"><h2 className="text-center text-2xl font-bold">Common questions</h2><div className="mx-auto mt-6 max-w-3xl divide-y divide-slate-200 border-y border-slate-200">{['When does fulfilment begin?','How fast is delivery?','What information will I need?','Where can I track my order?'].map((q,i)=><details key={q} open={i===1} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between font-bold">{q}<Icon name="chevron-down" className="transition group-open:rotate-180"/></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Fulfilment starts after payment confirmation. Timing and any required customer information are shown on each product page.</p></details>)}</div></Container>
  <section className="border-t border-blue-200 bg-blue-50"><Container className="flex flex-col gap-5 py-9 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-bold">Ready to find your next tool?</h2><p className="mt-1 text-slate-600">Browse trusted digital access with clear delivery.</p></div><Link to="/shop" className="inline-flex items-center justify-center gap-2 rounded-card bg-primary px-5 py-3 font-bold text-white">Explore tools <Icon name="arrow-right" className="size-4"/></Link></Container></section>
</>}
