import { Link } from 'react-router-dom'
import { orderService } from '../services'
import { Container } from '../components/layout/Container'
import { EmptyState } from '../components/feedback'
import { Icon } from '../components/ui/Icon'
import { OrderResultCard } from '../components/checkout/OrderResultCard'

export function OrderFailedPage(){
  const order=orderService.getLastAttempt()
  if(!order)return <Container className="py-16"><EmptyState title="No failed order attempt found" description="Return to your cart to safely continue checkout." action={<Link to="/cart" className="inline-flex items-center gap-2 rounded-card bg-primary px-5 py-3 font-bold text-white"><Icon name="arrow-left" className="size-4"/>Return to cart</Link>}/></Container>
  return <Container className="max-w-5xl py-10">
    <header className="text-center"><span className="mx-auto grid size-16 place-items-center rounded-full border border-red-300 bg-red-50 text-danger"><Icon name="x" className="size-8"/></span><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-danger">Order not completed</p><h1 className="mt-2 text-3xl font-extrabold">We couldn’t complete your order</h1><p className="mx-auto mt-2 max-w-2xl text-slate-600">The demo order submission was interrupted. Nothing was confirmed and your cart is still available.</p><div className="mt-5 flex flex-wrap items-center justify-center gap-3 text-sm"><span>Attempt reference <b className="break-all">{order.reference}</b></span><button onClick={()=>void navigator.clipboard?.writeText(order.reference)} aria-label="Copy attempt reference" className="text-primary"><Icon name="copy" className="size-4"/></button><span className="hidden h-4 w-px bg-slate-300 sm:block"/><time className="text-slate-500">{new Date(order.createdAt).toLocaleString()}</time></div></header>
    <p className="my-7 flex flex-col gap-3 border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 sm:flex-row sm:items-center"><Icon name="alert-triangle" className="shrink-0"/><span className="flex-1">If you already initiated a payment elsewhere, do not pay again until you check its status or contact support.</span></p>
    <OrderResultCard order={order} title="Attempted order"/>
    <section className="mt-8"><div className="grid gap-6 lg:grid-cols-[1fr_17rem]"><div><h2 className="text-xl font-bold">What you can do</h2><div className="mt-5 grid gap-5 sm:grid-cols-3">{[['credit-card','Retry checkout','Choose an available demo method.'],['cart','Review your cart','Confirm items, quantities and email.'],['headphones','Get help','Share the attempt reference with support.']].map(([icon,title,text],index)=><div key={title} className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-blue-50 text-primary"><Icon name={icon as 'cart'}/></span><div><b>{index+1}. {title}</b><p className="mt-1 text-sm leading-5 text-slate-600">{text}</p></div></div>)}</div></div><aside className="border border-slate-200 bg-slate-50/60 p-4"><h3 className="font-bold">Common demo reasons</h3><ul className="mt-3 list-disc space-y-2 pl-4 text-xs leading-5 text-slate-600"><li>Controlled submission interruption</li><li>Incomplete required information</li><li>Unavailable selected method</li></ul></aside></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Link to="/checkout" className="rounded-card bg-primary px-5 py-3 text-center font-bold text-white">Retry checkout</Link><Link to="/cart" className="rounded-card border border-primary px-5 py-3 text-center font-bold text-primary">Return to cart</Link><a href="mailto:support@subly.example" className="px-5 py-3 text-center font-bold text-primary">Contact support</a></div></section>
  </Container>
}
