import { Link } from 'react-router-dom'
import { orderService } from '../services'
import { Container } from '../components/layout/Container'
import { EmptyState } from '../components/feedback'
import { Icon } from '../components/ui/Icon'
import { OrderResultCard } from '../components/checkout/OrderResultCard'

export function OrderSuccessPage(){
  const order=orderService.getLastOrder()
  if(!order)return <Container className="py-16"><EmptyState title="No recent order found" description="This page needs a valid order from the current checkout session." action={<Link to="/shop" className="inline-flex items-center gap-2 rounded-card bg-primary px-5 py-3 font-bold text-white">Continue shopping <Icon name="arrow-right" className="size-4"/></Link>}/></Container>
  return <Container className="max-w-5xl py-10">
    <header className="text-center"><span className="mx-auto grid size-16 place-items-center rounded-full border border-teal/40 bg-teal/10 text-emerald-600 shadow-[0_0_0_8px_rgba(45,212,191,.08)]"><Icon name="check" className="size-8"/></span><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-emerald-700">Order submitted</p><h1 className="mt-2 text-3xl font-extrabold">Order received</h1><p className="mx-auto mt-2 max-w-2xl text-slate-600">We received your demo order information. Fulfilment begins only after payment confirmation.</p><div className="mx-auto mt-6 grid max-w-2xl gap-3 border border-slate-200 bg-white p-4 text-left sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><span className="text-xs text-slate-500">Order reference</span><b className="mt-0.5 block break-all">{order.reference}</b></div><button onClick={()=>void navigator.clipboard?.writeText(order.reference)} className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><Icon name="copy" className="size-4"/>Copy</button><time className="text-xs text-slate-500">{new Date(order.createdAt).toLocaleString()}</time></div></header>
    <ol className="my-9 grid grid-cols-3 gap-2 text-center text-xs sm:text-sm">{[['circle-check','Order received','Details submitted.'],['clock','Payment review','Confirmation pending.'],['mail','Delivery','After confirmation.']].map(([icon,title,text],index)=><li key={title} className="relative"><div className={"mx-auto grid size-9 place-items-center rounded-full "+(index===0?'bg-emerald-500 text-white':index===1?'border-2 border-primary bg-blue-50 text-primary':'border border-slate-300 bg-white text-slate-400')}><Icon name={icon as 'clock'} className="size-4"/></div><b className={"mt-2 block "+(index===0?'text-emerald-700':index===1?'text-primary':'text-slate-500')}>{index+1}. {title}</b><p className="mt-1 text-slate-500">{text}</p></li>)}</ol>
    <p className="mb-5 flex items-start gap-3 border border-blue-200 bg-blue-50/70 p-4 text-sm text-primary"><Icon name="info" className="mt-0.5"/>Order receipt is not payment confirmation. Do not make another payment based on this demo status.</p>
    <OrderResultCard order={order} title="Items in your order"/>
    <section className="mt-8"><h2 className="text-xl font-bold">What happens next?</h2><div className="mt-5 grid gap-5 sm:grid-cols-3">{[['shield-check','We review the order','The selected demo payment state is recorded.'],['package','Fulfilment begins','Access preparation starts after confirmation.'],['mail','You receive updates','Order information is sent to your delivery email.']].map(([icon,title,text],index)=><div key={title} className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-card bg-blue-50 text-primary"><Icon name={icon as 'mail'}/></span><div><b>{index+1}. {title}</b><p className="mt-1 text-sm leading-5 text-slate-600">{text}</p></div></div>)}</div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/orders" className="rounded-card bg-primary px-5 py-3 text-center font-bold text-white">View order status</Link><Link to="/shop" className="rounded-card border border-primary px-5 py-3 text-center font-bold text-primary">Continue shopping</Link><a href="mailto:support@subly.example" className="px-5 py-3 text-center font-bold text-primary">Contact support</a></div></section>
  </Container>
}
