import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import type { Product } from '../types'
import { productService } from '../services'
import { products,categories } from '../data/mockData'
import { useCart } from '../features/cart'
import { Container } from '../components/layout/Container'
import { AppLogo } from '../components/storefront/AppLogo'
import { PriceDisplay } from '../components/storefront/PriceDisplay'
import { ProductCard } from '../components/storefront/ProductCard'
import { Button,Icon,Spinner } from '../components/ui'
import { ErrorState } from '../components/feedback'

export function ProductDetailPage(){
  const {slug=''}=useParams(); const [product,setProduct]=useState<Product|null|undefined>(); const [quantity,setQuantity]=useState(1); const cart=useCart(); const navigate=useNavigate()
  useEffect(()=>{void productService.getBySlug(slug).then(setProduct)},[slug])
  if(product===undefined)return <Container className="py-20 text-center"><Spinner label="Loading product"/></Container>
  if(!product)return <Container className="py-16"><ErrorState title="Product unavailable" description="We could not find this product. It may no longer be available."/><Link className="mt-5 inline-flex items-center gap-2 text-primary" to="/shop"><Icon name="arrow-left" className="size-4"/> Return to shop</Link></Container>
  const category=categories.find(c=>c.id===product.categoryId); const add=()=>cart.addItem(product,quantity); const buy=()=>{add();navigate('/cart')}
  return <>
    <Container className="py-7"><nav className="flex items-center gap-2 text-sm text-slate-500"><Link to="/" className="hover:text-primary">Home</Link><span>/</span><Link to="/shop" className="hover:text-primary">Shop</Link><span>/</span><span className="truncate text-slate-700">{product.name}</span></nav>
      <div className="mt-7 grid gap-8 lg:grid-cols-[1.45fr_.8fr]">
        <section>
          <div className="grid gap-6 sm:grid-cols-[9rem_1fr] sm:items-start"><div className="grid aspect-square place-items-center rounded-card border border-slate-200 bg-slate-50/60 p-5"><AppLogo product={product} className="size-full max-h-24 max-w-24"/></div><div><p className="text-sm font-semibold text-primary">{category?.name}</p><h1 className="mt-1 text-3xl font-extrabold leading-tight">{product.name} — 1 Month</h1><div className="mt-3 flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded bg-blue-50 px-2.5 py-1 text-xs font-semibold text-primary"><Icon name={product.deliveryType==='ready-made'?'zap':'package'} className="size-3.5"/>{product.deliveryType==='ready-made'?'Ready-made access':'Assisted activation'}</span><span className="inline-flex items-center gap-1.5 rounded bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700"><Icon name="shield-check" className="size-3.5"/>Verified listing</span></div><p className="mt-4 flex items-center gap-2 text-sm text-slate-600"><Icon name="star" className="size-4 fill-amber-400 stroke-amber-400"/><b className="text-slate-900">{product.rating}</b> ({product.reviewCount.toLocaleString()} reviews)</p></div></div>
          <p className="mt-7 max-w-3xl text-base leading-7 text-slate-700">{product.description}</p>
          <div className="mt-8 grid gap-6 border-t border-slate-200 pt-7 md:grid-cols-2"><section><h2 className="text-lg font-bold">What’s included</h2><ul className="mt-4 grid gap-3">{product.features.map(f=><li key={f} className="flex gap-2 text-sm text-slate-700"><span className="grid size-5 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Icon name="check" className="size-3"/></span>{f}</li>)}</ul></section><section><h2 className="text-lg font-bold">Delivery and validity</h2><dl className="mt-4 grid gap-4 text-sm"><div className="flex gap-3"><Icon name="clock" className="text-primary"/><div><dt className="font-semibold">Delivery estimate</dt><dd className="mt-1 text-slate-600">{product.deliveryMinutes}–{product.deliveryMinutes+5} minutes after confirmation</dd></div></div><div className="flex gap-3"><Icon name="file-check" className="text-primary"/><div><dt className="font-semibold">Access validity</dt><dd className="mt-1 text-slate-600">{product.validity}</dd></div></div>{product.deliveryType==='assisted'&&<div className="flex gap-3"><Icon name="user" className="text-primary"/><div><dt className="font-semibold">Customer information</dt><dd className="mt-1 text-slate-600">Required account details are collected during fulfilment.</dd></div></div>}</dl></section></div>
        </section>
        <aside className="h-fit border border-slate-200 bg-white p-6 shadow-[0_12px_35px_rgba(15,23,42,.08)] lg:sticky lg:top-24"><div className="flex items-center justify-between gap-3"><p className={product.available?'flex items-center gap-2 font-semibold text-emerald-700':'font-semibold text-danger'}><span className={"size-2 rounded-full "+(product.available?'bg-emerald-500':'bg-red-500')}/>{product.available?(product.stock+' available'):'Out of stock'}</p><span className="text-xs text-slate-500">USD</span></div><div className="mt-5"><PriceDisplay product={product} large/></div><label className="mt-6 block text-sm font-semibold" htmlFor="quantity">Quantity</label><div className="mt-2 inline-flex"><button onClick={()=>setQuantity(q=>Math.max(1,q-1))} className="grid size-11 place-items-center rounded-l-card border border-slate-200" aria-label="Decrease quantity"><Icon name="minus" className="size-4"/></button><input id="quantity" className="h-11 w-20 border-y border-slate-200 text-center" type="number" min="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)))}/><button onClick={()=>setQuantity(q=>q+1)} className="grid size-11 place-items-center rounded-r-card border border-slate-200" aria-label="Increase quantity"><Icon name="plus" className="size-4"/></button></div><div className="mt-6 flex justify-between border-y border-slate-200 py-4"><span className="font-semibold">Subtotal</span><b className="text-xl">{'$'}{(product.price*quantity).toFixed(2)}</b></div><Button onClick={buy} disabled={!product.available} className="mt-5 w-full">Buy now</Button><Button onClick={add} disabled={!product.available} variant="secondary" className="mt-2 w-full">Add to cart</Button><ul className="mt-6 grid gap-3 border-t border-slate-200 pt-5 text-sm text-slate-700">{[['lock','Secure checkout'],['shield-check','Buyer protection'],['truck','Clear delivery estimate'],['headphones','Support included']].map(([icon,label])=><li key={label} className="flex items-center gap-3"><Icon name={icon as 'lock'} className="size-4 text-primary"/>{label}</li>)}</ul></aside>
      </div>
      <section className="mt-14 border-t border-slate-200 pt-9"><h2 className="text-2xl font-bold">Related products</h2><div className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-4">{products.filter(p=>p.id!==product.id).slice(0,4).map(p=><ProductCard compact key={p.id} product={p}/>)}</div></section>
    </Container>
    <div className="sticky bottom-0 z-30 flex items-center justify-between gap-2 border-t border-slate-200 bg-white/95 p-3 shadow-[0_-8px_24px_rgba(15,23,42,.08)] backdrop-blur lg:hidden"><div className="min-w-0"><span className="text-xs text-slate-500">Subtotal</span><b className="block">{'$'}{(product.price*quantity).toFixed(2)}</b></div><Button onClick={buy} className="px-4">Buy now</Button><Button variant="secondary" onClick={add} className="px-4">Add</Button></div>
  </>
}
