export { HomePage } from './HomePage'
export { HowItWorksPage } from './HowItWorksPage'
export { ShopPage } from './ShopPage'
export { ProductDetailPage } from './ProductDetailPage'
export { CartPage } from './CartPage'
export { CheckoutPage } from './CheckoutPage'
export { OrderSuccessPage } from './OrderSuccessPage'
export { OrderFailedPage } from './OrderFailedPage'
