import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { categories,products } from '../data/mockData'
import { Container } from '../components/layout/Container'
import { ProductCard } from '../components/storefront/ProductCard'
import { AppLogo } from '../components/storefront/AppLogo'
import { EmptyState } from '../components/feedback'
import { Icon } from '../components/ui/Icon'

export function ShopPage(){
  const [params,setParams]=useSearchParams(); const [filtersOpen,setFiltersOpen]=useState(false)
  const query=params.get('q')??''; const category=params.get('category')??''; const sort=params.get('sort')??'popular'
  const visible=useMemo(()=>products.filter(p=>(!query||p.name.toLowerCase().includes(query.toLowerCase()))&&(!category||categories.find(c=>c.id===p.categoryId)?.slug===category)).sort((a,b)=>sort==='price-low'?a.price-b.price:sort==='price-high'?b.price-a.price:b.reviewCount-a.reviewCount),[query,category,sort])
  function update(key:string,value:string){const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);setParams(next)}
  return <>
    <section className="border-b border-blue-100 bg-blue-50/60"><Container className="grid gap-6 py-9 lg:grid-cols-[1fr_auto] lg:items-center"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Subly marketplace</p><h1 className="mt-2 text-4xl font-extrabold">Shop</h1><p className="mt-2 max-w-lg text-slate-600">Find trusted digital tools for work, learning and creativity.</p></div><div className="hidden items-center gap-3 lg:flex">{products.slice(0,6).map(p=><a key={p.id} href={'/product/'+p.slug} className="grid size-14 shrink-0 place-items-center rounded-card border border-slate-200 bg-white p-2 shadow-sm"><AppLogo product={p} className="size-9"/></a>)}</div></Container></section>
    <Container className="py-8">
      <div className="flex flex-wrap items-center gap-3"><div className="relative min-w-0 flex-1"><Icon name="search" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>update('q',e.target.value)} aria-label="Search catalog" placeholder="Search products" className="min-h-11 w-full rounded-card border border-slate-200 bg-white pl-10 pr-4"/></div><button onClick={()=>setFiltersOpen(v=>!v)} className="inline-flex min-h-11 items-center gap-2 rounded-card border border-slate-200 bg-white px-4 font-semibold lg:hidden"><Icon name="filter" className="size-4"/> Filters</button><label className="flex items-center gap-2 text-sm text-slate-500"><span className="hidden sm:inline">Sort:</span><select value={sort} onChange={e=>update('sort',e.target.value)} aria-label="Sort products" className="min-h-11 rounded-card border border-slate-200 bg-white px-3 text-slate-800"><option value="popular">Most popular</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div>
      <div className="mt-7 grid gap-7 lg:grid-cols-[14rem_1fr]">
        <aside className={(filtersOpen?'block':'hidden')+" h-fit border border-slate-200 bg-white p-4 lg:sticky lg:top-24 lg:block"}><div className="flex items-center justify-between"><h2 className="font-bold">Categories</h2><Icon name="grid" className="size-4 text-slate-400"/></div><div className="mt-3 grid"><button onClick={()=>update('category','')} className={"flex w-full justify-between border-l-2 px-3 py-2.5 text-left text-sm "+(!category?'border-primary bg-blue-50 font-semibold text-primary':'border-transparent text-slate-700 hover:bg-slate-50')}>All products <span>{products.length}</span></button>{categories.map(c=><button key={c.id} onClick={()=>update('category',c.slug)} className={"flex w-full justify-between border-l-2 px-3 py-2.5 text-left text-sm "+(category===c.slug?'border-primary bg-blue-50 font-semibold text-primary':'border-transparent text-slate-700 hover:bg-slate-50')}>{c.name}<span>{products.filter(p=>p.categoryId===c.id).length}</span></button>)}</div><hr className="my-5 border-slate-200"/><h3 className="font-bold">Delivery type</h3><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" className="size-4 accent-primary"/> Ready-made access</label><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" className="size-4 accent-primary"/> Assisted activation</label><button onClick={()=>setParams({})} className="mt-6 w-full rounded-card border border-primary px-3 py-2 text-sm font-semibold text-primary">Clear filters</button></aside>
        <section><div className="flex items-end justify-between"><div><h2 className="text-2xl font-bold">{category?categories.find(c=>c.slug===category)?.name:'All products'}</h2><p className="mt-1 text-sm text-slate-500">{visible.length} products</p></div></div>{visible.length?<div className="mt-5 grid grid-cols-1 gap-4 min-[430px]:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="mt-5"><EmptyState title="No products found" description="Try another search or clear your filters." action={<button onClick={()=>setParams({})} className="rounded-card bg-primary px-4 py-2 text-white">Clear filters</button>}/></div>}<nav aria-label="Pagination" className="mt-8 flex justify-center gap-2"><button disabled className="rounded-card border border-slate-200 px-4 py-2 text-sm disabled:opacity-50">Previous</button><button aria-current="page" className="rounded-card bg-primary px-4 py-2 text-sm text-white">1</button><button className="rounded-card border border-slate-200 px-4 py-2 text-sm">2</button><button className="rounded-card border border-slate-200 px-4 py-2 text-sm">Next</button></nav></section>
      </div>
      <section className="mt-14 border-t border-slate-200 pt-10"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Recommended for you</h2><div className="hidden gap-2 sm:flex"><button aria-label="Previous recommendations" className="grid size-9 place-items-center rounded-full border border-slate-200"><Icon name="arrow-left" className="size-4"/></button><button aria-label="Next recommendations" className="grid size-9 place-items-center rounded-full border border-slate-200"><Icon name="arrow-right" className="size-4"/></button></div></div><div className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-4">{products.slice(8,12).map(p=><ProductCard compact key={p.id} product={p}/>)}</div></section>
    </Container>
  </>
}
